# Generated by Django 6.0 on 2025-12-08 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('exercise_id', models.CharField(db_index=True, max_length=255)),
                ('exercise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise_muscle_group', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=0, help_text='Orden dentro del día')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='8-12', help_text="Ej: '8-12', '10', '15-20'", max_length=50)),
                ('rest_time', models.IntegerField(default=60, help_text='Descanso en segundos entre sets')),
                ('set_type', models.CharField(choices=[('rectos', 'Sets rectos'), ('piramide', 'Pirámide'), ('drop', 'Drop sets'), ('super', 'Superseries')], default='straight', max_length=20)),
                ('target_weight', models.FloatField(blank=True, help_text='Peso objetivo en kg', null=True)),
                ('target_rpe', models.IntegerField(blank=True, help_text='RPE objetivo (1-10)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('coaching_tips', models.TextField(blank=True, help_text='Consejos para la ejecución', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejercicio de Rutina',
                'verbose_name_plural': 'Ejercicios de Rutina',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planificada', 'Planificada'), ('progreso', 'En progreso'), ('completo', 'Completada'), ('saltada', 'Saltada'), ('fallida', 'Fallida')], default='planned', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Calificación 1-5', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day_name', models.CharField(help_text='Ej: Día 1 - Pecho y Tríceps', max_length=100)),
                ('day_of_week', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True)),
                ('order', models.IntegerField(default=0, help_text='Orden dentro de la rutina')),
                ('warmup_duration', models.IntegerField(default=5, help_text='Duración calentamiento en minutos')),
                ('workout_duration', models.IntegerField(default=45, help_text='Duración entrenamiento en minutos')),
                ('cooldown_duration', models.IntegerField(default=5, help_text='Duración enfriamiento en minutos')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Día de Entrenamiento',
                'verbose_name_plural': 'Días de Entrenamiento',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('routine_type', models.CharField(choices=[('cuerpo_completo', 'Cuerpo Completo'), ('superior', 'Tren Superior'), ('inferior', 'Tren Inferior'), ('sup_inf', 'Tren Superior e Inferior'), ('bro_split', 'Por Músculo'), ('custom', 'Personalizada')], default='custom', max_length=50)),
                ('user_difficulty', models.CharField(default='principiante', max_length=20)),
                ('days', models.JSONField(default=list, help_text="Días de la semana: ['monday', 'wednesday', 'friday']")),
                ('weeks_duration', models.IntegerField(default=4, help_text='Duración en semanas')),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False, help_text='Si es una plantilla reutilizable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExercisePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sets_data', models.JSONField(default=list, help_text='[\n        {"set_number": 1, "reps": 10, "weight": 50, "rpe": 7},\n        {"set_number": 2, "reps": 8, "weight": 55, "rpe": 8}\n    ]')),
                ('total_volume', models.FloatField(blank=True, help_text='Volumen total (sets * reps * peso)', null=True)),
                ('avg_rpe', models.FloatField(blank=True, null=True)),
                ('pr_achieved', models.BooleanField(default=False)),
                ('pr_note', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('pain_level', models.IntegerField(blank=True, help_text='Nivel de dolor 1-10', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='routines.routineexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='routines.userworkoutsession')),
            ],
            options={
                'verbose_name': 'Desempeño de Ejercicio',
                'verbose_name_plural': 'Desempeños de Ejercicio',
            },
        ),
        migrations.AddField(
            model_name='userworkoutsession',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='routines.workoutday'),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.workoutday'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='routines.workoutroutine'),
        ),
        migrations.AddField(
            model_name='userworkoutsession',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='routines.workoutroutine'),
        ),
    ]
