# Generated by Django 6.0 on 2025-12-10 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaRutina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('musculo', models.CharField(choices=[('pierna', 'Pierna'), ('gluteo', 'Glúteo'), ('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('abdomen', 'Abdomen'), ('cuerpo_completo', 'Cuerpo Completo')], max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroserviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiaEjercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ejercicio_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('muscle_group', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('series', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='routines.diarutina')),
            ],
        ),
        migrations.AddField(
            model_name='diarutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='routines.rutina'),
        ),
    ]
